const STATUS = {
    GAME_SETUP:'GAME_SETUP',
    ROUND_START: 'ROUND_START',
    SHOW_QUESTION: 'SHOW_QUESTION',
    COLLECT_ANSWERS: 'COLLECT_ANSWERS',
    VOTING: 'VOTING',
    ROUND_END: 'ROUND_END',
    GAME_OVER: 'GAME_OVER'
}

module.exports = STATUS